[workspace]
resolver = "2"

members = [
    "libui-rs/iui",
    "libui-rs/ui-sys",
    "ats_cv",
    "ats_usb",
    "vision-module-gui",
]

# Enable optimizations for dependencies in dev profile
[profile.dev.package."*"]
opt-level = 3
